theme: minima
title: Your awesome title
author: GitHub User
email: semiloore.ezekiel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here is my first calculator on jekyll static site.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  semilooreezekiel # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
